global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  delorenzo:
    acme:
      email: "jaradd@gmail.com"
      storage: "./acme/delorenzo.family/challenges.json"
      dnsChallenge:
        provider: "namecheap"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  delosh:
    acme:
      email: "jaradd@gmail.com"
      storage: "./acme/delo.sh/challenges.json"
      dnsChallenge:
        provider: "namecheap"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  file:
    directory: "./config"
    watch: true

log:
  level: "DEBUG"
  filePath: "./traefik.log"

accessLog:
  filePath: "./access.log"
