http:
  routers:
    # DSM Router
    emma-dsm:
      entryPoints:
        - "websecure"
      rule: "Host(`delorenzo.family`) || Host(`emma.delorenzo.family`)"
      service: emma-dsm
      tls:
        certResolver: delorenzo
      middlewares:
        - secure-headers@file

    # Drive Router
    emma-drive:
      entryPoints:
        - "websecure"
      rule: "Host(`drive.delorenzo.family`)"
      service: emma-drive
      tls:
        certResolver: delorenzo
      middlewares:
        - secure-headers@file

  services:
    emma-dsm:
      loadBalancer:
        servers:
          - url: "http://192.168.1.50:5000"
        passHostHeader: true

    emma-drive:
      loadBalancer:
        servers:
          - url: "http://192.168.1.50:6690"
        passHostHeader: true